### ISSUE TITLE
Bug in python3 version

### ISSUE THREAD

**Issue by wil93** [WojciechMula/canvas2svg#2]
```
Traceback (most recent call last):
  File "a.py", line 18, in <module>
    saveImg()
  File "a.py", line 8, in saveImg
    canvasvg.saveall(nameSav, ts)
  File "/home/wil93/venvs/utils3/lib/python3.5/site-packages/canvasvg/canvasvg.py", line 284, in saveall
    for element in convert(doc, canvas, items, tounicode):
  File "/home/wil93/venvs/utils3/lib/python3.5/site-packages/canvasvg/canvasvg.py", line 113, in convert
    style["fill"] = HTMLcolor(canvas, get("fill"))
  File "/home/wil93/venvs/utils3/lib/python3.5/site-packages/canvasvg/canvasvg.py", line 539, in HTMLcolor
    r, g, b = ["%02x" % (c/256) for c in canvas.winfo_rgb(color)]
  File "/home/wil93/venvs/utils3/lib/python3.5/site-packages/canvasvg/canvasvg.py", line 539, in <listcomp>
    r, g, b = ["%02x" % (c/256) for c in canvas.winfo_rgb(color)]
TypeError: %x format: an integer is required, not float
```

In python 3 the `/` operator returns a float instead of an integer. I think `//` should be used.

**Comment by jrparadis** [comment]
why was this never fixed? :|

**Comment by WojciechMula** [comment]
@jrparadis It was fixed by the MR#4, linked above. Do you have this or similar problem?

**Comment by jrparadis** [comment]
Weird, I must of had some kind of conflict going on, reinstalling canvasvg a bunch of times didn't seem to update it. I had to go into canvasvg.py and change / to // to fix my error. Seems like it was local, trying it on a clean setup it worked fine.

**Comment by WojciechMula** [comment]
That's good it works fine for you. I checked what's on pip and for sure it was released.
